package drools
import drools.Samochod

rule "init"
when
then

 end


rule bledneDaty
when
rezerwacja: Rezerwacja(dlugosc<1)
then
 rezerwacja.rezerwacjaNiemozliwa=true;
 end

 rule dozwoloneDaty
 when
 rezerwacja: Rezerwacja(klient.czyDatySieNakladaja(rezerwacja,klient.rezerwacje)==false,dodanoDoKlienta==false)
 then rezerwacja.klient.rezerwacje.add(rezerwacja);
 rezerwacja.dodanoDoKlienta=true;
 update(rezerwacja);
  end

rule nakladanieDat
when
rezerwacja: Rezerwacja(klient.czyDatySieNakladaja(rezerwacja,klient.rezerwacje)==true, rezerwacjaNiemozliwa==false)
then rezerwacja.rezerwacjaNiemozliwa=true;
update(rezerwacja);
 end



 rule dostepnySamochodA
 when
 rezerwacja: Rezerwacja(preferencja == preferencja.A,samochod==null)
 samochod: Samochod(kategoria==kategoria.A,czyDatySieNakladaja(rezerwacja,samochod.rezerwacje)==false)
 then
 samochod.rezerwacje.add(rezerwacja);
 rezerwacja.samochod=samochod;
 update(rezerwacja);
 update(samochod);
 end

 rule brakAutaA
 when
 rezerwacja: Rezerwacja(preferencja == preferencja.A,samochod==null)
 samochod: Samochod(czyDatySieNakladaja(rezerwacja,samochod.rezerwacje)==true)
 then
 rezerwacja.stawka-=10;
 rezerwacja.preferencja=Samochod.Kategoria.B;;
 update(rezerwacja);
 end



  rule dostepnySamochodB
  when
  rezerwacja: Rezerwacja(preferencja == preferencja.B,samochod==null)
  samochod: Samochod(kategoria==kategoria.B,czyDatySieNakladaja(rezerwacja,samochod.rezerwacje)==false)
  then
  samochod.rezerwacje.add(rezerwacja);
  rezerwacja.samochod=samochod;
  rezerwacja.stawka+=10;
  update(rezerwacja);
   update(samochod);
  end

  rule brakAutaB
   when
   rezerwacja: Rezerwacja(preferencja == preferencja.B,samochod==null)
   samochod: Samochod(czyDatySieNakladaja(rezerwacja,samochod.rezerwacje)==true)
   then
   rezerwacja.stawka-=10;
   rezerwacja.preferencja=Samochod.Kategoria.D;
   update(rezerwacja);
   end

   rule dostepnySamochodD
   when
   rezerwacja: Rezerwacja(preferencja == preferencja.D,samochod==null)
   samochod: Samochod(kategoria==kategoria.D,czyDatySieNakladaja(rezerwacja,samochod.rezerwacje)==false)
   then
   samochod.rezerwacje.add(rezerwacja);
   rezerwacja.samochod=samochod;
   rezerwacja.stawka+=20;
   update(rezerwacja);
    update(samochod);
   end

   rule brakAutaD
    when
    rezerwacja: Rezerwacja(preferencja == preferencja.D,samochod==null)
    samochod: Samochod(czyDatySieNakladaja(rezerwacja,samochod.rezerwacje)==true)
    then
    rezerwacja.rezerwacjaNiemozliwa=true;
    update(rezerwacja);
    end


  rule wypozyczenieNiemozliwe
           when
           rezerwacja:Rezerwacja(rezerwacjaNiemozliwa==true)

           then
           System.out.println(rezerwacja.nazwa+ " dokonana przez "+rezerwacja.klient.nazwa+" jest niemozliwa");

            end


rule WynajemOd1Do3
when
rezerwacja: Rezerwacja(zwrot!=null,dlugosc<4, rezerwacjaNiemozliwa==false)
then
 rezerwacja.stawka+=69;
 rezerwacja.zwrot.stawkaKM=1;
 end

 rule WynajemPowyzej3
 when
 rezerwacja: Rezerwacja(zwrot!=null,dlugosc>3, rezerwacjaNiemozliwa==false)
 then
  rezerwacja.stawka+=59;
  rezerwacja.zwrot.stawkaKM=0.5;
  end


  rule fotelik
  when
  rezerwacja: Rezerwacja(fotelik==true, rezerwacjaNiemozliwa==false)
  then
   rezerwacja.wypozyczenie+=10;
   end

  rule bagaznik
    when
    rezerwacja: Rezerwacja(bagaznik==true, rezerwacjaNiemozliwa==false)
    then
     rezerwacja.wypozyczenie+=10;
     end

   rule znizka
      when
      rezerwacja: Rezerwacja(klient.lojalnosciowy==true ,fotelik==true || bagaznik== true, rezerwacjaNiemozliwa==false)
      then
      rezerwacja.wypozyczenie-=10;
       end

    rule brakKolpakow
        when
        rezerwacja: Rezerwacja(zwrot!=null,rezerwacjaNiemozliwa==false, zwrot.zgubioneKolpaki>0)
        then
        rezerwacja.zwrot.sumaZwrot+=20*rezerwacja.zwrot.zgubioneKolpaki;
        end

    rule brakDowodu
            when
            rezerwacja: Rezerwacja(zwrot!=null,rezerwacjaNiemozliwa==false, zwrot.brakDowodu==true)
            then
            rezerwacja.zwrot.sumaZwrot+=500;
            end

     rule opoznienie
        when
        rezerwacja: Rezerwacja(zwrot!=null,rezerwacjaNiemozliwa==false,opoznienie>0)
        then
        rezerwacja.zwrot.sumaZwrot+=rezerwacja.opoznienie*rezerwacja.stawka*3;
         end


    rule wypozyczenie
    when
    rezerwacja:Rezerwacja(zwrot!=null,rezerwacjaNiemozliwa==false,samochod!=null)
    then
     rezerwacja.wypozyczenie+=(int)rezerwacja.dlugosc*rezerwacja.stawka;
     rezerwacja.zwrot.sumaZwrot+=(int)rezerwacja.zwrot.przejechaneKM*rezerwacja.zwrot.stawkaKM;
     System.out.println("Dla "+rezerwacja.nazwa+ " klienta "+rezerwacja.klient.nazwa+":");
     System.out.println("SUMA Wypozyczenie " + rezerwacja.wypozyczenie+"zł"+" SUMA Oddanie " + rezerwacja.zwrot.sumaZwrot+"zł");
     System.out.println("SUMA  " + (rezerwacja.wypozyczenie+ rezerwacja.zwrot.sumaZwrot)+"zł");
     System.out.println("Przydzielono wolne auto z kategorii: "+rezerwacja.samochod.kategoria);
     System.out.println();
     end














